# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7a8f578627bc65a6d2d8e838bd34a5d6fd3b98d549472ea7d005d577d3e1ca37347eb33847eaba95418f51fc352383cdaa0b77493b4dda80f3acce4a655c2e92

test:
  secret_key_base: e9868b044fb8ae2ebc16563db569e593e7a5532d9b365f88d2e7c960a7dec9f34c0db125ab8e7e634115ba39fdb3d332fa4cb0a63d6a94af1b93d78e06dcb137

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
